/**
 * Public AI-credit contract and presentation helpers.
 *
 * The browser renders only the balance, plan limits, reset instants and cost guidance returned by
 * the server. It never decides a plan, entitlement, charge or operation price.
 */
import { PLAN_CATALOG, type PlanId } from './plans';

export type SubscriptionStatus = 'none' | 'active' | 'past_due' | 'canceled';
export type OperationCostStatus = 'charged' | 'already_charged' | 'not_charged';

export function billingStatusLabel(status: SubscriptionStatus): string {
  switch (status) {
    case 'active': return 'Active';
    case 'past_due': return 'Past due';
    case 'canceled': return 'Canceled';
    default: return 'Not connected';
  }
}

export interface PublicCredits {
  plan: PlanId;
  subscriptionStatus: SubscriptionStatus;
  availableCredits: number;
  dailyRemaining: number;
  dailyLimit: number;
  monthlyRemaining: number;
  monthlyLimit: number;
  nextDailyReset: string;
  nextMonthlyReset: string;
}

export interface PublicOperationCost {
  credits: number;
  status: OperationCostStatus;
}

/** These examples/ranges are generated by the server's validated-operation classifier. */
export interface PublicCreditCostGuide {
  formCreate: { min: number; max: number; standard: number; complexMin: number };
  formEdit: { min: number; max: number; singleChange: number; majorMin: number };
}

function record(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null;
}

function count(value: unknown): number | null {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 && value <= 1_000_000 ? value : null;
}

function instant(value: unknown): string | null {
  return typeof value === 'string' && value.length <= 40 && !Number.isNaN(Date.parse(value)) ? value : null;
}

/** Fail closed: an unreadable balance is never rendered as a number the user might trust. */
export function parseCredits(value: unknown): PublicCredits | null {
  const row = record(record(value)?.credits) ?? record(value);
  if (!row) return null;
  const plan = row.plan === 'pro' ? 'pro' : row.plan === 'free' ? 'free' : null;
  const subscriptionStatus: SubscriptionStatus | null =
    row.subscriptionStatus === 'none' || row.subscriptionStatus === 'active' ||
    row.subscriptionStatus === 'past_due' || row.subscriptionStatus === 'canceled'
      ? row.subscriptionStatus
      : null;
  const available = count(row.availableCredits);
  const daily = count(row.dailyRemaining);
  const dailyLimit = count(row.dailyLimit);
  const monthly = count(row.monthlyRemaining);
  const monthlyLimit = count(row.monthlyLimit);
  const nextDaily = instant(row.nextDailyReset);
  const nextMonthly = instant(row.nextMonthlyReset);
  if (!plan || !subscriptionStatus || available === null || daily === null || dailyLimit === null ||
      monthly === null || monthlyLimit === null || !nextDaily || !nextMonthly ||
      daily > dailyLimit || monthly > monthlyLimit || available !== daily + monthly ||
      (plan === 'free' && monthlyLimit !== 0)) return null;
  return {
    plan, subscriptionStatus, availableCredits: available,
    dailyRemaining: daily, dailyLimit, monthlyRemaining: monthly, monthlyLimit,
    nextDailyReset: nextDaily, nextMonthlyReset: nextMonthly,
  };
}

function guideEntry(value: unknown, keys: readonly string[]): number[] | null {
  const row = record(value);
  if (!row) return null;
  const values = keys.map(key => count(row[key]));
  return values.some(item => item === null) ? null : values as number[];
}

/** Parse only the bounded, human-facing guide returned with GET /api/credits. */
export function parseCreditCostGuide(value: unknown): PublicCreditCostGuide | null {
  const outer = record(value);
  const row = record(outer?.costGuide) ?? outer;
  if (!row) return null;
  const create = guideEntry(row.formCreate, ['min', 'max', 'standard', 'complexMin']);
  const edit = guideEntry(row.formEdit, ['min', 'max', 'singleChange', 'majorMin']);
  if (!create || !edit) return null;
  const [createMin, createMax, standard, complexMin] = create;
  const [editMin, editMax, singleChange, majorMin] = edit;
  if (createMin < 1 || createMin > standard || standard > createMax || createMin > complexMin || complexMin > createMax ||
      editMin < 1 || editMin > singleChange || singleChange > editMax || editMin > majorMin || majorMin > editMax) return null;
  return {
    formCreate: { min: createMin, max: createMax, standard, complexMin },
    formEdit: { min: editMin, max: editMax, singleChange, majorMin },
  };
}

/** Parse the operation receipt attached by the server to interpretation results. */
export function parseOperationCost(value: unknown): PublicOperationCost | null {
  const row = record(record(value)?.operationCost) ?? record(value);
  if (!row) return null;
  const credits = count(row.credits);
  const status = row.status === 'charged' || row.status === 'already_charged' || row.status === 'not_charged'
    ? row.status
    : null;
  if (credits === null || !status || (status === 'not_charged' ? credits !== 0 : credits < 1)) return null;
  return { credits, status };
}

export function creditSummary(credits: PublicCredits): string {
  if (credits.plan === 'pro') {
    return `${credits.dailyRemaining} of ${credits.dailyLimit} daily · ${credits.monthlyRemaining} of ${credits.monthlyLimit} monthly`;
  }
  return `${credits.dailyRemaining} of ${credits.dailyLimit} credits left today`;
}

/**
 * Human wording for the next reset, computed from the server's instant (never the browser clock).
 * The count is floored so Intake never promises credits later than they actually arrive.
 */
export function resetInterval(iso: string, now: Date = new Date()): string {
  const at = Date.parse(iso);
  if (Number.isNaN(at)) return 'soon';
  const hours = Math.max(0, Math.floor((at - now.getTime()) / 3_600_000));
  if (hours < 1) return 'in under an hour';
  if (hours < 24) return `in ${hours} hour${hours === 1 ? '' : 's'}`;
  const days = Math.floor(hours / 24);
  return `in ${days} day${days === 1 ? '' : 's'}`;
}

export function resetLabel(iso: string, now: Date = new Date()): string {
  return `resets ${resetInterval(iso, now)}`;
}

/** `insufficient_credits` is a product state, not an error the user caused. */
export function isInsufficientCredits(code: string | undefined): boolean {
  return code === 'insufficient_credits';
}

/**
 * What to say when an operation cannot be started because nothing is left. It names the state and,
 * when the balance is readable, when the next daily allowance arrives (the server's instant, never
 * the browser clock). Pro never implies a monthly-credit fallback.
 */
export function insufficientCreditsMessage(credits: PublicCredits | null, now: Date = new Date()): string {
  if (!credits) {
    return 'You have used every credit available right now. Daily credits reset every day at 00:00 UTC. Nothing was created or changed.';
  }
  const dailyReset = resetInterval(credits.nextDailyReset, now);
  if (credits.plan === 'pro') {
    const monthlyReset = resetInterval(credits.nextMonthlyReset, now);
    return `You have used all ${credits.dailyLimit} daily credits and the ${credits.monthlyLimit}-credit Pro monthly reserve. Daily credits reset ${dailyReset}; monthly credits reset ${monthlyReset}. Nothing was created or changed.`;
  }
  return `You have used today's ${credits.dailyLimit} free credits. Daily credits reset ${dailyReset}. Pro adds a ${PLAN_CATALOG.pro.monthlyCredits}-credit monthly reserve. Nothing was created or changed.`;
}
